version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: prodUser
      POSTGRES_PASSWORD: prodPassword
      POSTGRES_DB: HiringSystemProductionDB
    expose:
      - "5432"
    ports:
      - "5432:5432"

  backend: #spring-boot
    image: hiringsystem-backend
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - "8081:8081"
    env_file:
      - .env.email

  frontend: #nextjs
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.production
    image: hiringsystem-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

