/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2i2rI4w3g51
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function ApplicationsList() {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <Table className="min-w-full divide-y divide-gray-200">
          <TableHeader>
            <TableRow>
              <TableHead>Candidate</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Actions</TableHead>
              <TableHead>Resume</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium">
                John Doe
                <br />
                <span className="text-sm text-gray-500">john.doe@example.com</span>
              </TableCell>
              <TableCell>
                <Badge className="text-green-800 bg-green-100 rounded-full px-2">Pending</Badge>
              </TableCell>
              <TableCell>2023-11-23</TableCell>
              <TableCell>
                <div className="flex space-x-2">
                  <Button className="bg-green-500 text-white">Accept</Button>
                  <Button className="bg-red-500 text-white">Reject</Button>
                  <Button className="bg-gray-400 text-white">Erase</Button>
                </div>
              </TableCell>
              <TableCell>
                <Link className="text-blue-500 hover:underline" href="#" target="_blank">
                  View Resume
                </Link>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">
                Jane Smith
                <br />
                <span className="text-sm text-gray-500">jane.smith@example.com</span>
              </TableCell>
              <TableCell>
                <Badge className="text-red-800 bg-red-100 rounded-full px-2">Rejected</Badge>
              </TableCell>
              <TableCell>2023-10-30</TableCell>
              <TableCell>
                <div className="flex space-x-2">
                  <Button className="bg-green-500 text-white">Accept</Button>
                  <Button className="bg-red-500 text-white">Reject</Button>
                  <Button className="bg-gray-400 text-white">Erase</Button>
                </div>
              </TableCell>
              <TableCell>
                <Link className="text-blue-500 hover:underline" href="#" target="_blank">
                  View Resume
                </Link>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">
                Alex Johnson
                <br />
                <span className="text-sm text-gray-500">alex.johnson@example.com</span>
              </TableCell>
              <TableCell>
                <Badge className="text-green-800 bg-green-100 rounded-full px-2">Accepted</Badge>
              </TableCell>
              <TableCell>2023-12-01</TableCell>
              <TableCell>
                <div className="flex space-x-2">
                  <Button className="bg-green-500 text-white">Accept</Button>
                  <Button className="bg-red-500 text-white">Reject</Button>
                  <Button className="bg-gray-400 text-white">Erase</Button>
                </div>
              </TableCell>
              <TableCell>
                <Link className="text-blue-500 hover:underline" href="#" target="_blank">
                  View Resume
                </Link>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
